<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mayankas-MacBook-Air.local" failures="1" tests="13" name="Test" time="0.066" errors="0" timestamp="2024-06-21T16:42:25 IST">
  <testcase classname="com.qa.TestNG.Class2nd" name="carLoanAPIPage" time="0.005"/>
  <testcase classname="com.qa.TestNG.Class2nd" name="carLoanMobilePage" time="0.001"/>
  <testcase classname="com.qa.TestNG.Class2nd" name="carLoanWebPage" time="0.001"/>
  <testcase classname="com.qa.TestNG.Class1st" name="firstMethod" time="0.001"/>
  <testcase classname="com.qa.TestNG.Class1st" name="secondMethod" time="0.001"/>
  <testcase classname="com.qa.TestNG.Class3rd" name="excludehomeLoanAPIPage" time="0.001"/>
  <testcase classname="com.qa.TestNG.Class3rd" name="excludehomeLoanMobilePage" time="0.001"/>
  <testcase classname="com.qa.TestNG.Class3rd" name="excludehomeLoanWebage" time="0.0"/>
  <testcase classname="com.qa.TestNG.Class3rd" name="homeLoanAPIPage" time="0.001"/>
  <testcase classname="com.qa.TestNG.Class3rd" name="homeLoanMobilePage" time="0.0"/>
  <testcase classname="com.qa.TestNG.Class3rd" name="homeLoanWebPage" time="0.001"/>
  <testcase classname="com.qa.TestNG.Class4th" name="firstMethod" time="0.004"/>
  <testcase classname="com.qa.TestNG.Class4th" name="secondMethod" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.TestNG.Class4th.secondMethod(Class4th.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- secondMethod -->
</testsuite> <!-- Test -->
